[rosetta] Mempool Endpoint
harmony-one/harmony pull request #3339
Opened 2020-09-11 06:55 UTC by janet-harmony

Implements `/mempool` & `/mempool/transaction`
The transaction fetch implementation utilizes an "estimated" version of the finalized transaction receipt, which assumes transaction success.
No test file, because `formatTransaction` is already tested in `block_test.go`.

Example:
```
$ curl -X POST --data '{
    "network_identifier": {
      "blockchain": "Harmony",
      "network": "Testnet",
      "sub_network_identifier": {
        "network": "shard 1",
          "metadata": {
            "is_beacon": false
          }
      }
    }}' http://localhost:9798/mempool | jq
{
  "transaction_identifiers": [
    {
      "hash": "0x445113f5e313e3a388829ff1d47650a5deb6f9964a2f1c9e894ed6bc7af0abb2"
    }
  ]
}
```
```
$ curl -X POST --data '{
    "network_identifier": {
      "blockchain": "Harmony",
      "network": "Testnet",
      "sub_network_identifier": {
        "network": "shard 1",
          "metadata": {
            "is_beacon": false
          }
      }
    },
    "transaction_identifier": {
        "hash": "0x445113f5e313e3a388829ff1d47650a5deb6f9964a2f1c9e894ed6bc7af0abb2"
    }}' http://localhost:9798/mempool/transaction | jq
{
  "transaction": {
    "transaction_identifier": {
      "hash": "0x445113f5e313e3a388829ff1d47650a5deb6f9964a2f1c9e894ed6bc7af0abb2"
    },
    "operations": [
      {
        "operation_identifier": {
          "index": 0
        },
        "type": "Gas",
        "status": "success",
        "account": {
          "address": "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
          "metadata": {
            "hex_address": "0x15a128e599b74842BCcBa860311Efa92991bffb5"
          }
        },
        "amount": {
          "value": "-21000000000000",
          "currency": {
            "symbol": "ONE",
            "decimals": 18
          }
        }
      },
      {
        "operation_identifier": {
          "index": 1
        },
        "related_operations": [
          {
            "index": 0
          }
        ],
        "type": "Transfer",
        "status": "success",
        "account": {
          "address": "one1zksj3evekayy90xt4psrz8h6j2v3hla4qwz4ur",
          "metadata": {
            "hex_address": "0x15a128e599b74842BCcBa860311Efa92991bffb5"
          }
        },
        "amount": {
          "value": "-100000000000000000000",
          "currency": {
            "symbol": "ONE",
            "decimals": 18
          }
        }
      },
      {
        "operation_identifier": {
          "index": 2
        },
        "related_operations": [
          {
            "index": 1
          }
        ],
        "type": "Transfer",
        "status": "success",
        "account": {
          "address": "one155jp2y76nazx8uw5sa94fr0m4s5aj8e5xm6fu3",
          "metadata": {
            "hex_address": "0xA5241513DA9F4463F1d4874b548dFBAC29D91f34"
          }
        },
        "amount": {
          "value": "100000000000000000000",
          "currency": {
            "symbol": "ONE",
            "decimals": 18
          }
        }
      }
    ]
  }
```

2020-09-11 08:40 UTC, Daniel-VDM commented
PR is related to #3210

2020-09-11 19:24 UTC, rlan35 approved these changes

2020-09-12 05:22 UTC, Daniel-VDM requested changes
Looks good, just take care of the error with collect reward txs

2020-09-12 05:22 UTC, Daniel-VDM commented on rosetta/services/mempool.go
> +		Logs:              []*hmyTypes.Log{},
Missing logs here for collect reward transaction will cause an error, reference:
https://github.com/harmony-one/harmony/blob/e74ab0bc0aa2d2fd39d7dadaa96ca5a5d4777fe9/rosetta/services/block.go#L1004-L1024

Can just create some dummy logs with the collect reward topic and have the value at 0.

2020-09-12 07:35 UTC, Daniel-VDM approved these changes

2020-09-23 23:56 UTC, merged