[RPC] Return EVM error when using the call RPC
harmony-one/harmony pull request #3375
Opened 2020-09-30 06:49 UTC by janet-harmony

The JS SDK will need to be modified to display the error message to the developer.

Example error response from failed `require` statement :
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "evm: execution reverted"
  }
}
```

2020-09-30 07:01 UTC, JackyWYX requested changes
Looks good to me.

2020-09-30 07:02 UTC, JackyWYX approved these changes

2020-09-30 19:28 UTC, LeoHChen commented
will it cause any compatibility issue during upgrade process?

2020-10-01 01:06 UTC, janet-harmony commented
> will it cause any compatibility issue during upgrade process?

No, shouldn't. The changes are only internal to each node & does not affect messages in the network.

2020-10-01 05:21 UTC, rlan35 commented on core/state_transition.go
> +func (st *StateTransition) TransitionDb() (*ExecutionResult, error) {
can you make the return the struct, instead of pointer? To loose the client's burden of checking nil and avoid potential crash.

2020-10-01 05:27 UTC, rlan35 commented
> Part 1 of [EVM Error changes](https://gist.github.com/janet-harmony/980f6cacc3e398a0a116b17fa79c6fd6)
> 
> **Reverted changes to RPC response to keep backwards compatibility**
> Example error response from failed `require` statement :
> 
> ```
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "result": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b56616c75652066616c7365000000000000000000000000000000000000000000"
> }
> ```

Did you check the the vmErr contains the require() statement string?   I remember I always got something like "transaction reverted" for the vmErr without detailed data in `utils.Logger().Info().Err(vmErr).Msg("VM returned with error")`

2020-10-01 05:44 UTC, janet-harmony commented
The VMErr field is `transaction reverted`, but the return data from the EVM is the error message in the `require(false, "error")` statement.
So the current implementation of `hmy_call` already supports returning error messages.

2020-10-02 19:51 UTC, rlan35 commented
> The VMErr field is `transaction reverted`, but the return data from the EVM is the error message in the `require(false, "error")` statement.
> So the current implementation of `hmy_call` already supports returning error messages.
> 
> Changed to a struct, but the consumer should always check the error anyways to be safe, which is the only place the ExecutionResult returns as nil.

If we can, we should choose to systematically avoid potential mistakes which could cause crashes. Sounds good on the return data.

2020-10-02 19:51 UTC, rlan35 approved these changes

2020-10-02 19:51 UTC, merged