feat: make log to console as optional
harmony-one/harmony pull request #4208
Opened 2022-06-26 08:06 UTC by jasonyic

## Issue
harmony only support log to file and `lumberjack` rotation make `ln -sf /dev/stdout zerolog-harmony.log` impossible when running in `docker` and `kubernetes`, which log everything to console.

## Proposed changes
add a boolean configuration `Console` in `Log` to provide the option to log to console only

## Test 
`make test-go` passed. nut i have to rename `travis_go_checker.sh` to `travis_checker.sh`, since `localnet-test` seems looking for the wrong test file.
```
PASS
ok  	github.com/harmony-one/harmony/staking/types/test	0.073s
?   	github.com/harmony-one/harmony/staking/verify	[no test files]
?   	github.com/harmony-one/harmony/test/chain	[no test files]
?   	github.com/harmony-one/harmony/test/chain/reward	[no test files]
?   	github.com/harmony-one/harmony/test/chain/vrf	[no test files]
?   	github.com/harmony-one/harmony/test/helpers	[no test files]
?   	github.com/harmony-one/harmony/webhooks	[no test files]
go test succeeded.
```

2022-06-27 04:27 UTC, jasonyic commented
#4212

2022-06-28 07:51 UTC, MaxMustermann2 requested changes
Thanks, just a couple of comments.

2022-06-28 07:51 UTC, MaxMustermann2 commented on Makefile
> +export LD_LIBRARY_PATH:=$(TOP)/bls/lib:$(TOP)/mcl/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/gmp/lib/:/opt/homebrew/opt/openssl/lib:/usr/lib
Why has this been changed?

2022-06-28 07:51 UTC, MaxMustermann2 commented on cmd/harmony/config_test.go
> +	Console = false
nitpick: Please use consistent indentation.

2022-06-28 07:51 UTC, MaxMustermann2 commented on cmd/harmony/config_test.go
> +  RotateMaxAge = 0
nit: Please remove the extra spaces.

2022-06-28 07:51 UTC, MaxMustermann2 commented on go.sum
> -github.com/json-iterator/go v1.1.10 h1:Kz6Cvnvv2wGdaG/V8yMvfkmNiXq9Ya2KUv4rouJJr68=
Why has this been removed?

2022-06-28 07:51 UTC, MaxMustermann2 commented on go.sum
> -github.com/modern-go/reflect2 v1.0.1 h1:9f412s+6RmYXLWZSEzVVgPGK7C2PphHj5RJrvfx9AWI=
Why has this been removed?

2022-06-28 07:51 UTC, MaxMustermann2 commented on p2p/stream/protocols/sync/message/msg.pb.go
> +// 	protoc-gen-go v1.25.0
Why has this been changed? This PR should not impact this file AFAIK.

2022-06-29 05:32 UTC, MaxMustermann2 commented
Thank you. Just one last change now, could you add a config file migration like this one?
https://github.com/harmony-one/harmony/blob/main/cmd/harmony/config_migrations.go#L224-L231

2022-06-29 07:08 UTC, jasonyic commented
> Thank you. Just one last change now, could you add a config file migration like this one? https://github.com/harmony-one/harmony/blob/main/cmd/harmony/config_migrations.go#L224-L231

done, thank you for taking time to review.

2022-06-29 11:28 UTC, jasonyic commented
is this a typo for the rate limit? `RateLimterEnabled`
[RPCOpt]
  DebugEnabled = false
  EthRPCsEnabled = true
  LegacyRPCsEnabled = true
  RateLimterEnabled = true

2022-06-29 13:57 UTC, MaxMustermann2 approved these changes

2022-06-29 13:57 UTC, MaxMustermann2 commented
Thanks for your PR!

> is this a typo for the rate limit?

Appears to be, but it seems to be consistently used throughout the config file and the source code so I wouldn't bother too much with it.

2022-06-29 14:38 UTC, Frozen approved these changes

2022-06-30 06:01 UTC, jasonyic commented
> Thanks for your PR!
> 
> > is this a typo for the rate limit?
> 
> Appears to be, but it seems to be consistently used throughout the config file and the source code so I wouldn't bother too much with it.

got it.

2022-07-31 17:48 UTC, rlan35 approved these changes

2022-07-31 17:48 UTC, merged