Consensus Mask. Removed unnecessary argument.
harmony-one/harmony pull request #4466
Opened 2023-07-15 20:01 UTC by Frozen

NewMask doesn't accept `myKey` anymore.

2023-07-16 01:16 UTC, ONECasey commented
Whats this supposed to be merged to `main`? @Frozen

2023-07-17 20:19 UTC, adsorptionenthalpy approved these changes

2023-07-17 22:14 UTC, ONECasey commented
@Frozen. Does this go into `main`?

2023-07-17 22:15 UTC, ONECasey requested changes
@Frozen Does this go into `main`?

2023-07-19 17:04 UTC, Frozen commented
> @Frozen Does this go into `main`?

Changed to dev

2023-07-20 06:23 UTC, MaxMustermann2 reviewed
Small comment but otherwise looks good. I confirmed with Konstantin elsewhere that the parameter is not used meaningfully anywhere at all.

2023-07-20 06:23 UTC, MaxMustermann2 commented on crypto/bls/mask.go
>  // bitmask to 1 (enabled).
Can you update the documentation to remove the content `If a public key is given...` ?

2023-07-21 02:50 UTC, sophoah approved these changes
LGTM

2023-07-21 02:59 UTC, merged